build_mode = "release"
target_adapters = ["circom"]
target_platforms = [
    "android",
    "ios",
]
ios = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
]
android = ["aarch64-linux-android"]
