name: Build

on:
    push:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

env:
    CARGO_TERM_COLOR: always

jobs:
    build-macOS-v1-89-0:
        runs-on: macos-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        steps:
            - uses: actions/checkout@v5
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: "1.89.0"
                  targets: aarch64-apple-ios
            - name: Run tests
              run: cargo build --target aarch64-apple-ios
    build-macOS-v1-82-0:
        runs-on: macos-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        steps:
            - uses: actions/checkout@v5
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: "1.82.0"
                  targets: aarch64-apple-ios
            - name: Run tests
              run: cargo build --target aarch64-apple-ios
